// <auto-generated />
using System;
using CommentsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommentsApp.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241011121918_add seed")]
    partial class addseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommentsApp.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 10, 10, 23, 7, 43, 539, DateTimeKind.Unspecified).AddTicks(9238),
                            Text = "Est maxime aut quis vel ut porro sed eligendi aut. Rerum hic ut deleniti odit omnis corrupti id. Optio est dolorum sit aliquam fugit nihil excepturi.",
                            UserId = 59
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 10, 7, 20, 53, 55, 537, DateTimeKind.Unspecified).AddTicks(1960),
                            Text = "Eligendi dolor consequatur culpa sint qui laudantium perspiciatis.",
                            UserId = 30
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 10, 4, 18, 12, 44, 991, DateTimeKind.Unspecified).AddTicks(8981),
                            Text = "Sed et ut nisi sapiente fuga consequuntur eos laudantium. A consequuntur repellendus doloremque ut. Quia quod est quos a hic. Id eveniet officia et. Adipisci deleniti magnam.",
                            UserId = 59
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 10, 9, 4, 6, 15, 339, DateTimeKind.Unspecified).AddTicks(9813),
                            Text = "Praesentium architecto dolorem fugiat.",
                            UserId = 38
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 10, 9, 18, 46, 19, 729, DateTimeKind.Unspecified).AddTicks(4723),
                            Text = "Voluptate blanditiis qui aut velit et aut.\nEius labore aut ipsum atque maxime ducimus autem.\nOdit rerum voluptatibus.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 10, 5, 8, 43, 10, 191, DateTimeKind.Unspecified).AddTicks(4907),
                            Text = "provident",
                            UserId = 64
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 10, 5, 22, 26, 50, 57, DateTimeKind.Unspecified).AddTicks(2337),
                            Text = "Et nemo incidunt.",
                            UserId = 37
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 10, 9, 21, 46, 14, 705, DateTimeKind.Unspecified).AddTicks(6462),
                            Text = "Vero molestias dolorem consequuntur rem ut.\nEt qui delectus reiciendis sit quisquam praesentium.",
                            UserId = 38
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 10, 4, 12, 11, 12, 43, DateTimeKind.Unspecified).AddTicks(9311),
                            Text = "Ut modi velit eius reprehenderit libero ut.\nVoluptates consequatur qui dignissimos fugiat unde consequatur occaecati et.\nIllum excepturi totam est culpa.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 10, 9, 23, 50, 29, 239, DateTimeKind.Unspecified).AddTicks(9493),
                            Text = "Ducimus itaque architecto eligendi deleniti. Sapiente numquam expedita quis. Praesentium et id expedita est repellat.",
                            UserId = 46
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 10, 6, 5, 31, 50, 762, DateTimeKind.Unspecified).AddTicks(9034),
                            Text = "Accusamus debitis voluptas minus ipsa fuga facilis quia nostrum error. Et ex aut non omnis delectus optio. Temporibus eos numquam nulla ex perferendis qui. Non beatae voluptate nobis veniam id molestias et velit pariatur. Aspernatur suscipit similique sed repellat accusamus eos nulla.",
                            UserId = 39
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 10, 7, 12, 33, 5, 162, DateTimeKind.Unspecified).AddTicks(6189),
                            Text = "Ducimus velit molestiae beatae expedita doloremque atque.\nEnim tempore quo ipsa rerum aut voluptatem ab.\nVoluptates minus voluptates eius mollitia magnam eius voluptas numquam.",
                            UserId = 68
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 10, 9, 11, 49, 13, 82, DateTimeKind.Unspecified).AddTicks(4666),
                            Text = "ut",
                            UserId = 33
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 10, 7, 11, 51, 15, 984, DateTimeKind.Unspecified).AddTicks(4755),
                            Text = "Vitae soluta molestiae voluptate. Consequatur doloremque repellendus distinctio. Quos fugit maiores perspiciatis autem provident est voluptatibus voluptas. Pariatur hic nihil placeat dignissimos. Maiores unde sapiente. Et velit aperiam facilis ut quis.",
                            UserId = 41
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 10, 8, 12, 14, 41, 610, DateTimeKind.Unspecified).AddTicks(6078),
                            Text = "Vel deserunt consequatur fugiat.\nDoloribus tenetur autem.\nEt incidunt excepturi sint eum dolores aut soluta delectus.\nVel atque qui.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 10, 9, 2, 21, 43, 346, DateTimeKind.Unspecified).AddTicks(6796),
                            Text = "Nisi nemo quam.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 10, 4, 15, 50, 51, 364, DateTimeKind.Unspecified).AddTicks(8880),
                            Text = "Voluptatem eaque ea laboriosam repudiandae nisi et aperiam quia.",
                            UserId = 27
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 10, 4, 1, 49, 43, 123, DateTimeKind.Unspecified).AddTicks(969),
                            Text = "Occaecati quaerat aut qui quod sed blanditiis neque.",
                            UserId = 55
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 10, 4, 7, 49, 29, 773, DateTimeKind.Unspecified).AddTicks(8734),
                            Text = "Ut sit est.",
                            UserId = 52
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 10, 4, 6, 21, 37, 771, DateTimeKind.Unspecified).AddTicks(4064),
                            Text = "Est commodi ut omnis quidem voluptas dolorum quae ut.\nCum aliquid sunt est error.\nQuia accusantium consequatur.",
                            UserId = 56
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 10, 8, 14, 28, 45, 625, DateTimeKind.Unspecified).AddTicks(9222),
                            Text = "Voluptatem voluptas autem.\nQuam iure eius iusto soluta.\nSapiente sequi repudiandae quia omnis reiciendis.\nVoluptate illum qui enim voluptatibus et recusandae blanditiis error dignissimos.",
                            UserId = 66
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 10, 9, 7, 22, 24, 336, DateTimeKind.Unspecified).AddTicks(3000),
                            Text = "Odit sint ullam facere enim iure ullam et a.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 10, 4, 7, 40, 1, 100, DateTimeKind.Unspecified).AddTicks(6752),
                            Text = "Voluptate dolorem aut ut iure qui iste aut.\nId ipsa voluptate.\nAccusamus at earum nostrum explicabo amet.\nAt ut laborum sunt ducimus officia et.\nVero corporis quasi enim minima quis quae in error.",
                            UserId = 53
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 10, 5, 21, 30, 54, 18, DateTimeKind.Unspecified).AddTicks(8673),
                            Text = "Et natus quo et rerum.\nEst sit quibusdam ratione atque quae.\nQuia omnis nemo illum quibusdam quia omnis rerum maxime.",
                            UserId = 53
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 10, 7, 19, 31, 39, 384, DateTimeKind.Unspecified).AddTicks(7683),
                            Text = "sequi",
                            UserId = 61
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 10, 9, 16, 42, 54, 715, DateTimeKind.Unspecified).AddTicks(6408),
                            Text = "Eos occaecati exercitationem iste consequatur illo vero perspiciatis.",
                            UserId = 52
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 10, 4, 13, 13, 44, 488, DateTimeKind.Unspecified).AddTicks(2746),
                            Text = "voluptas",
                            UserId = 45
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 10, 5, 8, 34, 13, 782, DateTimeKind.Unspecified).AddTicks(6116),
                            Text = "Officiis nulla aliquam nulla sequi praesentium. Ex quia saepe voluptatibus omnis autem id. Quidem ipsum aut sapiente placeat.",
                            UserId = 31
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 10, 9, 13, 17, 46, 12, DateTimeKind.Unspecified).AddTicks(2513),
                            Text = "Nesciunt voluptatem est aut labore.\nUt necessitatibus distinctio hic laborum consequuntur dolor voluptatibus.\nEst velit dolore.\nOfficiis assumenda pariatur culpa.",
                            UserId = 54
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 10, 4, 20, 7, 7, 529, DateTimeKind.Unspecified).AddTicks(9350),
                            Text = "Et atque quaerat et nisi aut in repellat odio facere.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 10, 10, 1, 56, 26, 924, DateTimeKind.Unspecified).AddTicks(7693),
                            Text = "vitae",
                            UserId = 64
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 10, 7, 10, 44, 13, 393, DateTimeKind.Unspecified).AddTicks(1361),
                            Text = "Reprehenderit accusantium et reiciendis eaque natus laboriosam.\nQuas nemo odio dicta eveniet et fugiat.\nEa ea rerum.\nQuia sed maiores et voluptatem.\nConsequatur perferendis autem debitis porro molestiae aut optio earum necessitatibus.",
                            UserId = 67
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2024, 10, 9, 9, 21, 36, 901, DateTimeKind.Unspecified).AddTicks(1687),
                            Text = "molestias",
                            UserId = 20
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2024, 10, 6, 8, 35, 18, 904, DateTimeKind.Unspecified).AddTicks(3264),
                            Text = "eligendi",
                            UserId = 20
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2024, 10, 10, 8, 44, 10, 765, DateTimeKind.Unspecified).AddTicks(5335),
                            Text = "Enim quae atque qui assumenda dignissimos amet amet eaque quis.",
                            UserId = 67
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2024, 10, 6, 15, 5, 27, 338, DateTimeKind.Unspecified).AddTicks(9458),
                            Text = "voluptas",
                            UserId = 59
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2024, 10, 5, 17, 2, 27, 812, DateTimeKind.Unspecified).AddTicks(8391),
                            Text = "Velit sapiente rerum.\nEveniet sit vel.\nSunt magni nostrum et ex.\nReprehenderit nihil maxime qui doloribus sequi provident.",
                            UserId = 45
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2024, 10, 6, 11, 42, 15, 730, DateTimeKind.Unspecified).AddTicks(5157),
                            Text = "Magni ipsam cum ducimus ducimus odit atque. Sequi aut consequatur ut officia perspiciatis reprehenderit. Explicabo inventore maxime tempore. Et et fuga eaque incidunt mollitia ea. Est quia aspernatur voluptate ut illo et.",
                            UserId = 49
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2024, 10, 7, 9, 29, 6, 743, DateTimeKind.Unspecified).AddTicks(7903),
                            Text = "Aut iusto eum suscipit.\nAut dignissimos voluptas ex esse cumque aut repellat hic.",
                            UserId = 51
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2024, 10, 7, 10, 48, 36, 786, DateTimeKind.Unspecified).AddTicks(8795),
                            Text = "velit",
                            UserId = 30
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2024, 10, 5, 8, 55, 54, 863, DateTimeKind.Unspecified).AddTicks(626),
                            Text = "ut",
                            UserId = 43
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2024, 10, 5, 10, 40, 36, 257, DateTimeKind.Unspecified).AddTicks(5203),
                            Text = "Et quos voluptas deserunt ducimus autem natus.",
                            UserId = 47
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2024, 10, 9, 4, 21, 17, 629, DateTimeKind.Unspecified).AddTicks(3142),
                            Text = "quam",
                            UserId = 34
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2024, 10, 8, 3, 36, 43, 881, DateTimeKind.Unspecified).AddTicks(5544),
                            Text = "Mollitia modi enim molestias.",
                            UserId = 69
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2024, 10, 4, 5, 37, 58, 209, DateTimeKind.Unspecified).AddTicks(296),
                            Text = "Unde provident ut laudantium soluta consequatur.",
                            UserId = 61
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2024, 10, 5, 18, 27, 52, 999, DateTimeKind.Unspecified).AddTicks(7274),
                            Text = "Error tenetur iusto voluptas.\nQuia perspiciatis blanditiis sequi error aspernatur assumenda voluptatem quibusdam ex.",
                            UserId = 46
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2024, 10, 9, 21, 44, 50, 422, DateTimeKind.Unspecified).AddTicks(7800),
                            Text = "exercitationem",
                            UserId = 33
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2024, 10, 5, 15, 24, 42, 990, DateTimeKind.Unspecified).AddTicks(3325),
                            Text = "Inventore numquam voluptates debitis provident a aspernatur voluptas eius. Vero sed nesciunt. Corporis sit qui hic et vero.",
                            UserId = 42
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2024, 10, 7, 15, 10, 28, 112, DateTimeKind.Unspecified).AddTicks(8124),
                            Text = "libero",
                            UserId = 36
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2024, 10, 5, 10, 46, 5, 179, DateTimeKind.Unspecified).AddTicks(4137),
                            Text = "assumenda",
                            UserId = 34
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2024, 10, 6, 9, 15, 10, 183, DateTimeKind.Unspecified).AddTicks(4512),
                            Text = "quisquam",
                            UserId = 64
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2024, 10, 7, 11, 45, 38, 361, DateTimeKind.Unspecified).AddTicks(5631),
                            Text = "Nam molestiae velit totam aliquam unde.\nItaque sequi consequatur.\nSaepe fugit dolorem quia animi.\nVoluptas nostrum dolores et.\nIllo accusamus voluptas natus nihil doloribus eos.",
                            UserId = 35
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2024, 10, 9, 21, 43, 18, 750, DateTimeKind.Unspecified).AddTicks(7365),
                            Text = "Repellendus accusantium ipsa iure adipisci numquam reiciendis minus quia. Et officiis ipsum. Pariatur sed tempore suscipit velit et quia fugit accusamus voluptas. Optio quia fugit et. Et provident nisi nisi ipsa sit iste qui magni.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2024, 10, 7, 18, 34, 34, 430, DateTimeKind.Unspecified).AddTicks(7829),
                            Text = "Et blanditiis reprehenderit blanditiis eos sit facilis dolorem laboriosam recusandae.\nLibero sequi porro dolore dolores sunt eos.\nLaboriosam magnam ut non dolorem non libero natus pariatur sed.",
                            UserId = 36
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2024, 10, 10, 3, 32, 51, 238, DateTimeKind.Unspecified).AddTicks(2778),
                            Text = "Quaerat nobis nemo libero reiciendis dolor amet optio consectetur voluptate.\nQuis accusantium voluptas sunt harum maiores exercitationem culpa.\nNobis et molestiae.\nNon rem blanditiis quibusdam sapiente consequatur voluptatum.\nNon eius blanditiis error consectetur nihil rerum voluptatem voluptatem iste.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2024, 10, 5, 23, 12, 7, 101, DateTimeKind.Unspecified).AddTicks(7210),
                            Text = "iste",
                            UserId = 52
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2024, 10, 10, 0, 36, 52, 28, DateTimeKind.Unspecified).AddTicks(3167),
                            Text = "Aliquid dolorem vitae nihil dolore praesentium possimus.",
                            UserId = 57
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2024, 10, 5, 20, 5, 56, 804, DateTimeKind.Unspecified).AddTicks(5089),
                            Text = "Minus amet recusandae illum dignissimos consequatur.\nAut dignissimos natus voluptate et rerum.\nEst aut corrupti ut.",
                            UserId = 61
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2024, 10, 5, 11, 16, 28, 549, DateTimeKind.Unspecified).AddTicks(6895),
                            Text = "Nemo pariatur tempora ut asperiores consequatur dignissimos veniam.\nDolorem omnis qui necessitatibus amet voluptatem.\nFugiat sit ut.",
                            UserId = 26
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2024, 10, 9, 8, 30, 22, 902, DateTimeKind.Unspecified).AddTicks(8338),
                            Text = "Sed id tenetur aliquam dolorem cum officia accusamus nisi. Et delectus numquam quo reprehenderit velit repellat. Doloremque id consequuntur enim quo. Tempora vero asperiores ea aliquam voluptatem et. Adipisci voluptate at quaerat at consectetur sed.",
                            UserId = 55
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2024, 10, 6, 7, 50, 27, 95, DateTimeKind.Unspecified).AddTicks(7512),
                            Text = "Natus exercitationem eveniet repellat earum. Dolores sint qui. Eligendi aut ut. Doloremque enim nobis sit laborum.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2024, 10, 4, 3, 20, 25, 396, DateTimeKind.Unspecified).AddTicks(2960),
                            Text = "est",
                            UserId = 60
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2024, 10, 9, 21, 24, 46, 14, DateTimeKind.Unspecified).AddTicks(1845),
                            Text = "nisi",
                            UserId = 60
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2024, 10, 4, 0, 41, 14, 161, DateTimeKind.Unspecified).AddTicks(7170),
                            Text = "Ut fugiat deleniti inventore recusandae.",
                            UserId = 67
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2024, 10, 10, 15, 41, 37, 569, DateTimeKind.Unspecified).AddTicks(2193),
                            Text = "Magni aliquid qui ratione.",
                            UserId = 55
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2024, 10, 7, 8, 11, 22, 389, DateTimeKind.Unspecified).AddTicks(8483),
                            Text = "Neque aut sit illo ad in est.",
                            UserId = 44
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2024, 10, 5, 22, 55, 39, 522, DateTimeKind.Unspecified).AddTicks(4062),
                            Text = "sit",
                            UserId = 60
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2024, 10, 10, 7, 48, 10, 898, DateTimeKind.Unspecified).AddTicks(6625),
                            Text = "In cum blanditiis aut quam.",
                            UserId = 33
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2024, 10, 5, 5, 17, 53, 313, DateTimeKind.Unspecified).AddTicks(4522),
                            Text = "Porro nihil tenetur voluptatem aliquam fuga sunt non.",
                            UserId = 58
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2024, 10, 8, 16, 14, 49, 461, DateTimeKind.Unspecified).AddTicks(6548),
                            Text = "Voluptatem a iusto temporibus sunt.\nEt reiciendis expedita totam et asperiores.\nRem quaerat architecto itaque labore et.",
                            UserId = 42
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2024, 10, 10, 8, 52, 54, 559, DateTimeKind.Unspecified).AddTicks(5544),
                            Text = "Dignissimos quis incidunt eveniet alias dicta eaque saepe soluta.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2024, 10, 4, 7, 44, 48, 356, DateTimeKind.Unspecified).AddTicks(2486),
                            Text = "Ut harum impedit nobis atque impedit.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2024, 10, 9, 22, 4, 41, 531, DateTimeKind.Unspecified).AddTicks(3069),
                            Text = "quia",
                            UserId = 61
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2024, 10, 9, 11, 53, 10, 957, DateTimeKind.Unspecified).AddTicks(8210),
                            Text = "Qui culpa eveniet reiciendis maiores odit doloribus esse laboriosam. Et necessitatibus dolorum in quia doloribus suscipit. Omnis sed nemo. Vel ut dolorum enim ut exercitationem ab. Maxime ipsum incidunt sed enim aspernatur. Fugit quis reprehenderit.",
                            UserId = 47
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2024, 10, 8, 15, 55, 7, 265, DateTimeKind.Unspecified).AddTicks(9342),
                            Text = "Dolorum qui dignissimos vel.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2024, 10, 9, 13, 47, 21, 543, DateTimeKind.Unspecified).AddTicks(1164),
                            Text = "Et voluptatem non.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2024, 10, 4, 23, 47, 29, 653, DateTimeKind.Unspecified).AddTicks(5968),
                            Text = "Sed eligendi consequatur itaque assumenda eligendi expedita esse. Accusantium aut modi quod consequatur. Sunt dolorem sed aliquid et eum occaecati enim porro et. Odit repudiandae cum aliquam saepe sit possimus distinctio.",
                            UserId = 29
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2024, 10, 6, 2, 45, 42, 268, DateTimeKind.Unspecified).AddTicks(9097),
                            Text = "Molestiae neque doloremque fugit repellat qui. Ullam optio suscipit iusto necessitatibus. In omnis rerum. Quam et aperiam et officia maxime id aut.",
                            UserId = 26
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2024, 10, 5, 10, 8, 52, 154, DateTimeKind.Unspecified).AddTicks(9124),
                            Text = "Dolor consequuntur dolore.",
                            UserId = 56
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2024, 10, 8, 10, 6, 56, 641, DateTimeKind.Unspecified).AddTicks(7589),
                            Text = "Quibusdam voluptate enim voluptatem et ea voluptate culpa.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2024, 10, 9, 4, 24, 14, 433, DateTimeKind.Unspecified).AddTicks(3442),
                            Text = "Omnis quas iusto adipisci. Laboriosam laboriosam quam exercitationem odit accusamus. Vel eius sint quia consectetur voluptatem sed voluptatem repudiandae. Minima voluptatem reprehenderit. Nam sit dolorem quos rerum labore.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2024, 10, 7, 10, 54, 29, 958, DateTimeKind.Unspecified).AddTicks(1284),
                            Text = "Est ab ut blanditiis dicta eius quas ullam.",
                            UserId = 40
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2024, 10, 4, 19, 17, 20, 413, DateTimeKind.Unspecified).AddTicks(842),
                            Text = "Quis illo eius est praesentium nostrum eligendi tempora quis et. Cum sequi aliquam et laudantium et nam omnis repudiandae voluptas. Eos aut placeat veritatis optio culpa reiciendis.",
                            UserId = 57
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2024, 10, 8, 10, 31, 33, 41, DateTimeKind.Unspecified).AddTicks(1947),
                            Text = "Autem iusto quam unde harum.\nLaborum ducimus ea magnam ea dolor non delectus cumque fugiat.\nVoluptas ut ut quae at sint esse earum qui.\nAut dolore ut sint ea adipisci et.",
                            UserId = 42
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2024, 10, 6, 22, 12, 41, 0, DateTimeKind.Unspecified).AddTicks(5230),
                            Text = "vitae",
                            UserId = 21
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2024, 10, 9, 23, 35, 46, 538, DateTimeKind.Unspecified).AddTicks(9632),
                            Text = "Fugit rerum ducimus ut magni minus.",
                            UserId = 63
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2024, 10, 6, 9, 53, 4, 351, DateTimeKind.Unspecified).AddTicks(2820),
                            Text = "Numquam et earum occaecati consequatur. Ut autem quas sed eos suscipit tenetur. Et quas suscipit temporibus eligendi consequatur nobis.",
                            UserId = 68
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2024, 10, 7, 3, 14, 22, 597, DateTimeKind.Unspecified).AddTicks(3383),
                            Text = "Aut voluptatem eos incidunt aut sunt officiis vitae voluptatibus dolorum.\nNulla eaque voluptatum quibusdam quia quibusdam consectetur.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2024, 10, 9, 6, 38, 10, 120, DateTimeKind.Unspecified).AddTicks(8020),
                            Text = "Et tempora perspiciatis ex minima ut.",
                            UserId = 51
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2024, 10, 7, 15, 38, 27, 761, DateTimeKind.Unspecified).AddTicks(2364),
                            Text = "Eaque harum ut excepturi enim aut.\nLaudantium officiis id dignissimos doloribus.\nFacere eius aut deleniti ipsum totam.",
                            UserId = 43
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2024, 10, 10, 18, 14, 32, 332, DateTimeKind.Unspecified).AddTicks(2936),
                            Text = "Velit quidem est maxime exercitationem quidem ducimus.",
                            UserId = 56
                        },
                        new
                        {
                            Id = 111,
                            CreatedAt = new DateTime(2024, 10, 4, 5, 40, 1, 204, DateTimeKind.Unspecified).AddTicks(7416),
                            Text = "Repellat nulla dolorem eligendi cupiditate.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 112,
                            CreatedAt = new DateTime(2024, 10, 6, 15, 40, 24, 655, DateTimeKind.Unspecified).AddTicks(9957),
                            Text = "dolorum",
                            UserId = 58
                        },
                        new
                        {
                            Id = 113,
                            CreatedAt = new DateTime(2024, 10, 10, 13, 59, 50, 202, DateTimeKind.Unspecified).AddTicks(4638),
                            Text = "illo",
                            UserId = 50
                        },
                        new
                        {
                            Id = 114,
                            CreatedAt = new DateTime(2024, 10, 10, 3, 30, 56, 927, DateTimeKind.Unspecified).AddTicks(5319),
                            Text = "sequi",
                            UserId = 23
                        },
                        new
                        {
                            Id = 115,
                            CreatedAt = new DateTime(2024, 10, 5, 12, 14, 27, 754, DateTimeKind.Unspecified).AddTicks(4367),
                            Text = "Eaque est debitis culpa ex asperiores dolorem.\nAccusamus voluptate soluta dolores facere quis.",
                            UserId = 29
                        },
                        new
                        {
                            Id = 116,
                            CreatedAt = new DateTime(2024, 10, 9, 3, 40, 31, 824, DateTimeKind.Unspecified).AddTicks(8363),
                            Text = "Iure vero vel culpa in quidem qui.\nVelit nostrum distinctio repudiandae.\nUt odio aut illo illum earum minus.",
                            UserId = 68
                        },
                        new
                        {
                            Id = 117,
                            CreatedAt = new DateTime(2024, 10, 7, 2, 13, 27, 503, DateTimeKind.Unspecified).AddTicks(8649),
                            Text = "repudiandae",
                            UserId = 30
                        },
                        new
                        {
                            Id = 118,
                            CreatedAt = new DateTime(2024, 10, 6, 1, 50, 57, 194, DateTimeKind.Unspecified).AddTicks(4715),
                            Text = "Eaque quis molestiae maxime numquam dolorum cumque tempora. Deleniti rerum non omnis. Magni quia dolores aut repellendus ipsam. Magni delectus cumque facilis perspiciatis consequuntur nam. Consequatur voluptas porro nostrum unde quis et incidunt dolorem commodi. Id in eos laboriosam repellat occaecati non pariatur.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 119,
                            CreatedAt = new DateTime(2024, 10, 5, 16, 40, 51, 147, DateTimeKind.Unspecified).AddTicks(5321),
                            Text = "Sed sed voluptates ea.\nAspernatur tempore dolores eaque voluptas dolorem quidem tempora.\nNumquam ipsa non reiciendis voluptas id veritatis culpa doloribus ut.\nNihil quia suscipit ad mollitia adipisci et eum.",
                            UserId = 49
                        },
                        new
                        {
                            Id = 120,
                            CreatedAt = new DateTime(2024, 10, 10, 17, 32, 9, 909, DateTimeKind.Unspecified).AddTicks(4703),
                            Text = "Sint quas et est tempora optio.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 121,
                            CreatedAt = new DateTime(2024, 10, 5, 5, 35, 44, 418, DateTimeKind.Unspecified).AddTicks(433),
                            Text = "Asperiores aut vero est eum quisquam quasi.\nConsequuntur rerum omnis voluptatem aut laboriosam modi odio dolores ipsum.\nRerum neque repellendus in eligendi.\nVoluptatem quae quo rerum maxime incidunt.\nNon cupiditate laboriosam totam quod rem ut nam sint aut.",
                            UserId = 35
                        },
                        new
                        {
                            Id = 122,
                            CreatedAt = new DateTime(2024, 10, 7, 20, 11, 50, 132, DateTimeKind.Unspecified).AddTicks(2647),
                            Text = "Aliquid alias aliquam.\nAccusamus dignissimos magni.\nNon tempora neque magnam quia tempore.\nQuasi eum velit at.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 123,
                            CreatedAt = new DateTime(2024, 10, 6, 8, 48, 2, 852, DateTimeKind.Unspecified).AddTicks(6674),
                            Text = "facere",
                            UserId = 54
                        },
                        new
                        {
                            Id = 124,
                            CreatedAt = new DateTime(2024, 10, 9, 4, 12, 19, 657, DateTimeKind.Unspecified).AddTicks(9411),
                            Text = "Ea atque facere. Doloribus dolorem optio fugiat et et commodi deleniti quibusdam dicta. Labore culpa eius ratione. Quis minus et velit rerum reprehenderit rerum ut dolore iste. Delectus at aut beatae qui voluptatum.",
                            UserId = 30
                        },
                        new
                        {
                            Id = 125,
                            CreatedAt = new DateTime(2024, 10, 10, 22, 24, 2, 812, DateTimeKind.Unspecified).AddTicks(7173),
                            Text = "Odio facere ab quis nostrum commodi. Sint sed dignissimos possimus animi quo fuga natus laboriosam. Animi non ut. Architecto quia qui et temporibus aut in. Quis a consectetur sit necessitatibus exercitationem dolorem commodi excepturi. Ad voluptatum minus.",
                            UserId = 41
                        },
                        new
                        {
                            Id = 126,
                            CreatedAt = new DateTime(2024, 10, 7, 19, 43, 47, 2, DateTimeKind.Unspecified).AddTicks(5882),
                            Text = "magnam",
                            UserId = 28
                        },
                        new
                        {
                            Id = 127,
                            CreatedAt = new DateTime(2024, 10, 6, 9, 15, 58, 485, DateTimeKind.Unspecified).AddTicks(3015),
                            Text = "dolores",
                            UserId = 26
                        },
                        new
                        {
                            Id = 128,
                            CreatedAt = new DateTime(2024, 10, 5, 18, 28, 14, 478, DateTimeKind.Unspecified).AddTicks(6694),
                            Text = "Consequatur commodi in et maxime et ex voluptatum.",
                            UserId = 57
                        },
                        new
                        {
                            Id = 129,
                            CreatedAt = new DateTime(2024, 10, 4, 21, 10, 14, 551, DateTimeKind.Unspecified).AddTicks(6408),
                            Text = "Qui rerum sit qui aut iste quas.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 130,
                            CreatedAt = new DateTime(2024, 10, 4, 19, 49, 23, 67, DateTimeKind.Unspecified).AddTicks(6334),
                            Text = "Amet autem dolorum iste. Harum ut ullam omnis. Vitae non officia quo voluptas mollitia. Repellat voluptatibus est cupiditate rerum nam modi quia assumenda nesciunt. Sequi dolor facere a est velit totam.",
                            UserId = 38
                        },
                        new
                        {
                            Id = 131,
                            CreatedAt = new DateTime(2024, 10, 7, 18, 30, 22, 196, DateTimeKind.Unspecified).AddTicks(1421),
                            Text = "Excepturi amet aut. Et in aut voluptatem. Voluptates voluptas officiis accusamus hic facilis perspiciatis impedit qui.",
                            UserId = 41
                        },
                        new
                        {
                            Id = 132,
                            CreatedAt = new DateTime(2024, 10, 10, 3, 57, 39, 728, DateTimeKind.Unspecified).AddTicks(7364),
                            Text = "Qui qui rerum consequuntur sed dolor dolore qui.",
                            UserId = 55
                        },
                        new
                        {
                            Id = 133,
                            CreatedAt = new DateTime(2024, 10, 10, 17, 10, 43, 507, DateTimeKind.Unspecified).AddTicks(1130),
                            Text = "Suscipit quo rem ea. Delectus saepe temporibus dolore pariatur debitis dicta omnis. Et distinctio corrupti quis dolor facilis vero ipsa modi. Id adipisci et sit qui adipisci non. Consequatur est nemo. Ut aperiam nihil dolores culpa accusamus eveniet minus.",
                            UserId = 58
                        },
                        new
                        {
                            Id = 134,
                            CreatedAt = new DateTime(2024, 10, 8, 22, 44, 15, 47, DateTimeKind.Unspecified).AddTicks(6634),
                            Text = "Quia id tempora placeat reiciendis eius.",
                            UserId = 36
                        },
                        new
                        {
                            Id = 135,
                            CreatedAt = new DateTime(2024, 10, 5, 13, 38, 46, 246, DateTimeKind.Unspecified).AddTicks(922),
                            Text = "Non laboriosam debitis reprehenderit ab rerum omnis.\nConsequatur praesentium numquam.\nQui nam veniam et doloribus ratione.\nAutem optio est numquam eligendi expedita.\nLaudantium qui temporibus qui perferendis sunt voluptatem esse dolor nesciunt.\nVoluptatum nulla explicabo alias sapiente quam hic aut.",
                            UserId = 35
                        },
                        new
                        {
                            Id = 136,
                            CreatedAt = new DateTime(2024, 10, 8, 16, 16, 25, 71, DateTimeKind.Unspecified).AddTicks(1946),
                            Text = "eligendi",
                            UserId = 27
                        },
                        new
                        {
                            Id = 137,
                            CreatedAt = new DateTime(2024, 10, 4, 12, 47, 0, 855, DateTimeKind.Unspecified).AddTicks(6926),
                            Text = "consequuntur",
                            UserId = 26
                        },
                        new
                        {
                            Id = 138,
                            CreatedAt = new DateTime(2024, 10, 8, 12, 55, 59, 654, DateTimeKind.Unspecified).AddTicks(6211),
                            Text = "Minus vitae dolor dolorum. Omnis ducimus quia odit eaque. Consequuntur consequatur excepturi ullam reprehenderit temporibus.",
                            UserId = 56
                        },
                        new
                        {
                            Id = 139,
                            CreatedAt = new DateTime(2024, 10, 9, 15, 48, 44, 861, DateTimeKind.Unspecified).AddTicks(8123),
                            Text = "Ut consectetur vel ducimus rerum sed et.",
                            UserId = 68
                        },
                        new
                        {
                            Id = 140,
                            CreatedAt = new DateTime(2024, 10, 4, 22, 34, 54, 383, DateTimeKind.Unspecified).AddTicks(3938),
                            Text = "Aperiam sint quod voluptas sint vel.",
                            UserId = 53
                        },
                        new
                        {
                            Id = 141,
                            CreatedAt = new DateTime(2024, 10, 4, 13, 16, 13, 705, DateTimeKind.Unspecified).AddTicks(3289),
                            Text = "Id deserunt error repellendus.\nPariatur id suscipit amet ea eos animi iure necessitatibus.\nIpsum et iusto culpa nesciunt repudiandae unde et explicabo.\nEst sed voluptatum velit veritatis corrupti omnis mollitia eos.\nRepellendus rerum vero corporis sit tempora.\nCorporis sit quia repudiandae aliquid officiis quia non voluptatem.",
                            UserId = 41
                        },
                        new
                        {
                            Id = 142,
                            CreatedAt = new DateTime(2024, 10, 10, 15, 36, 49, 332, DateTimeKind.Unspecified).AddTicks(7218),
                            Text = "Non rem non quae. Voluptatem molestiae quia sint aspernatur. Dolore iusto aut. Autem magni error non inventore.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 143,
                            CreatedAt = new DateTime(2024, 10, 5, 17, 46, 59, 93, DateTimeKind.Unspecified).AddTicks(2617),
                            Text = "Distinctio aliquid velit ipsa illo voluptas. Pariatur voluptatem quaerat esse molestiae aliquam nihil delectus non. Aspernatur architecto voluptates odit. Aut molestiae tempora ullam ex eveniet. Rerum voluptatum omnis asperiores. Est voluptates est vitae et quaerat ut in.",
                            UserId = 28
                        },
                        new
                        {
                            Id = 144,
                            CreatedAt = new DateTime(2024, 10, 8, 19, 46, 55, 838, DateTimeKind.Unspecified).AddTicks(7397),
                            Text = "Vero sapiente consequuntur et tenetur nulla doloremque ipsam modi et. Illum facere atque officiis laborum. Dolor et non et illo. Quia explicabo incidunt. Cum nihil voluptatem ea inventore ex nihil et itaque. Debitis cupiditate nihil.",
                            UserId = 68
                        },
                        new
                        {
                            Id = 145,
                            CreatedAt = new DateTime(2024, 10, 4, 10, 0, 3, 993, DateTimeKind.Unspecified).AddTicks(1018),
                            Text = "Qui ut aut omnis commodi repellendus vero ut.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 146,
                            CreatedAt = new DateTime(2024, 10, 4, 13, 6, 0, 752, DateTimeKind.Unspecified).AddTicks(8295),
                            Text = "et",
                            UserId = 65
                        },
                        new
                        {
                            Id = 147,
                            CreatedAt = new DateTime(2024, 10, 5, 8, 39, 5, 287, DateTimeKind.Unspecified).AddTicks(7294),
                            Text = "Ex laborum sapiente. Numquam praesentium sit voluptatibus recusandae molestias iusto aliquam neque delectus. Et qui facere eum quia. Enim sint ea. Illo esse dolor optio aperiam sit.",
                            UserId = 65
                        },
                        new
                        {
                            Id = 148,
                            CreatedAt = new DateTime(2024, 10, 8, 14, 1, 51, 492, DateTimeKind.Unspecified).AddTicks(1298),
                            Text = "Laudantium dolor ut aut omnis autem molestiae minima.\nQuo voluptas aut molestiae ipsum molestias.\nQui mollitia asperiores ipsa.\nIste quos nesciunt quae sequi quis ut quia.\nQui corrupti ex dolorum dolorem laborum sint.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 149,
                            CreatedAt = new DateTime(2024, 10, 4, 3, 5, 43, 395, DateTimeKind.Unspecified).AddTicks(1653),
                            Text = "rerum",
                            UserId = 52
                        },
                        new
                        {
                            Id = 150,
                            CreatedAt = new DateTime(2024, 10, 6, 10, 19, 53, 471, DateTimeKind.Unspecified).AddTicks(4625),
                            Text = "Magnam cupiditate non perferendis voluptas non.\nSimilique aut et quis beatae omnis fuga molestias.\nTenetur saepe voluptatem aliquid dolorum nemo consequatur.",
                            UserId = 64
                        },
                        new
                        {
                            Id = 151,
                            CreatedAt = new DateTime(2024, 10, 9, 21, 32, 5, 572, DateTimeKind.Unspecified).AddTicks(6535),
                            Text = "magnam",
                            UserId = 57
                        },
                        new
                        {
                            Id = 152,
                            CreatedAt = new DateTime(2024, 10, 4, 9, 25, 24, 443, DateTimeKind.Unspecified).AddTicks(6482),
                            Text = "in",
                            UserId = 60
                        },
                        new
                        {
                            Id = 153,
                            CreatedAt = new DateTime(2024, 10, 10, 10, 19, 8, 629, DateTimeKind.Unspecified).AddTicks(8630),
                            Text = "Autem nemo voluptas et consequatur repellendus laborum quaerat voluptas.\nVoluptatem quisquam id ea nobis sunt.\nEos illum earum occaecati harum commodi.\nA non velit a sit totam dolores nesciunt.\nMaxime sequi est consequuntur voluptatem perspiciatis quo optio.\nSimilique numquam vero non perferendis et consequatur corrupti.",
                            UserId = 40
                        },
                        new
                        {
                            Id = 154,
                            CreatedAt = new DateTime(2024, 10, 5, 9, 8, 8, 736, DateTimeKind.Unspecified).AddTicks(7730),
                            Text = "Quod rerum sed veniam. Quis et non vero corporis aut alias doloribus quia eaque. Reprehenderit voluptatem voluptatibus et est et voluptatem repellendus molestiae repudiandae. Deserunt voluptas et ab quis possimus et. Cumque aut id nam laudantium ipsa. Impedit voluptates facere non accusantium mollitia voluptas non aut.",
                            UserId = 58
                        },
                        new
                        {
                            Id = 155,
                            CreatedAt = new DateTime(2024, 10, 7, 0, 26, 24, 677, DateTimeKind.Unspecified).AddTicks(7864),
                            Text = "Quibusdam sit at ut omnis veritatis sunt temporibus.\nMinus dolore corrupti autem suscipit.\nExpedita et occaecati velit a ex labore aperiam ut rerum.\nVoluptatem ipsam illo.",
                            UserId = 34
                        },
                        new
                        {
                            Id = 156,
                            CreatedAt = new DateTime(2024, 10, 4, 15, 42, 20, 369, DateTimeKind.Unspecified).AddTicks(6309),
                            Text = "doloremque",
                            UserId = 57
                        },
                        new
                        {
                            Id = 157,
                            CreatedAt = new DateTime(2024, 10, 6, 17, 9, 26, 289, DateTimeKind.Unspecified).AddTicks(4268),
                            Text = "Nihil voluptatibus est et expedita voluptatem veniam sed.\nAsperiores in ex aut veniam sint excepturi ipsam iste.\nTenetur vitae maxime quibusdam est.\nDelectus neque quia praesentium ab molestiae ad est.\nIllum eius incidunt iusto qui aut dolorum aliquid numquam enim.\nOptio dolor quis occaecati sint nihil aliquid autem.",
                            UserId = 66
                        },
                        new
                        {
                            Id = 158,
                            CreatedAt = new DateTime(2024, 10, 10, 10, 46, 56, 375, DateTimeKind.Unspecified).AddTicks(3944),
                            Text = "Sit eligendi vero architecto beatae facere error ullam qui voluptatem. Ullam minima aut aut quis suscipit. Non non aperiam eaque repellendus debitis nobis earum.",
                            UserId = 51
                        },
                        new
                        {
                            Id = 159,
                            CreatedAt = new DateTime(2024, 10, 9, 3, 51, 41, 916, DateTimeKind.Unspecified).AddTicks(2332),
                            Text = "Vero aperiam veniam magnam saepe. Perspiciatis enim praesentium nihil. Fugit doloremque illum modi ut perspiciatis. Dicta deserunt debitis et et repudiandae. Voluptates reiciendis iure eos. Atque in quod et.",
                            UserId = 50
                        },
                        new
                        {
                            Id = 160,
                            CreatedAt = new DateTime(2024, 10, 9, 8, 4, 1, 687, DateTimeKind.Unspecified).AddTicks(8731),
                            Text = "Dolores autem praesentium. Qui mollitia et. Inventore laudantium nihil vitae cumque vel magnam totam nihil. Consequatur aut maiores quia sequi dolores. Modi eaque autem incidunt quia.",
                            UserId = 67
                        },
                        new
                        {
                            Id = 161,
                            CreatedAt = new DateTime(2024, 10, 8, 3, 57, 2, 731, DateTimeKind.Unspecified).AddTicks(3913),
                            Text = "Et quam commodi fugiat ipsam tempora sequi sint molestiae et. Repellendus officia corrupti. Amet aut harum cupiditate aspernatur. Quidem voluptas minus animi natus unde cupiditate at quas totam.",
                            UserId = 28
                        },
                        new
                        {
                            Id = 162,
                            CreatedAt = new DateTime(2024, 10, 8, 8, 20, 51, 787, DateTimeKind.Unspecified).AddTicks(6452),
                            Text = "Veritatis omnis ab. Eum aliquam tempora cumque quis iusto ducimus rerum eveniet voluptatem. Id reprehenderit velit. Dolorem explicabo harum incidunt possimus cum harum et nihil delectus.",
                            UserId = 64
                        },
                        new
                        {
                            Id = 163,
                            CreatedAt = new DateTime(2024, 10, 4, 23, 21, 40, 396, DateTimeKind.Unspecified).AddTicks(5397),
                            Text = "Quia sit culpa facilis ut.\nVoluptate fuga dignissimos neque aut distinctio fuga eum.",
                            UserId = 41
                        },
                        new
                        {
                            Id = 164,
                            CreatedAt = new DateTime(2024, 10, 9, 8, 7, 29, 824, DateTimeKind.Unspecified).AddTicks(8654),
                            Text = "Veniam a et voluptatem exercitationem sed velit amet aut. Ea inventore quisquam nulla laborum ut placeat voluptatem. Non minima possimus totam amet et facilis sit.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 165,
                            CreatedAt = new DateTime(2024, 10, 6, 6, 32, 37, 632, DateTimeKind.Unspecified).AddTicks(7240),
                            Text = "Quia vero possimus. Eligendi aut quis dignissimos quasi. Id necessitatibus eaque odit reprehenderit vel perferendis.",
                            UserId = 66
                        },
                        new
                        {
                            Id = 166,
                            CreatedAt = new DateTime(2024, 10, 8, 21, 45, 3, 969, DateTimeKind.Unspecified).AddTicks(3169),
                            Text = "Deserunt non corrupti et magnam. Sit consectetur hic aut harum exercitationem rerum et. Quis quia id.",
                            UserId = 56
                        },
                        new
                        {
                            Id = 167,
                            CreatedAt = new DateTime(2024, 10, 6, 12, 5, 27, 738, DateTimeKind.Unspecified).AddTicks(6570),
                            Text = "Culpa ratione sapiente magnam. Doloribus nemo quia ut. Eveniet voluptatem tempora. Ducimus possimus rerum voluptatem debitis sunt quibusdam quaerat maxime. Non est est est. Aut qui velit quo autem voluptates aspernatur nostrum in voluptatibus.",
                            UserId = 30
                        },
                        new
                        {
                            Id = 168,
                            CreatedAt = new DateTime(2024, 10, 4, 3, 16, 32, 841, DateTimeKind.Unspecified).AddTicks(2507),
                            Text = "Numquam maiores animi eos ducimus.",
                            UserId = 57
                        },
                        new
                        {
                            Id = 169,
                            CreatedAt = new DateTime(2024, 10, 9, 16, 47, 50, 864, DateTimeKind.Unspecified).AddTicks(3062),
                            Text = "eaque",
                            UserId = 69
                        });
                });

            modelBuilder.Entity("CommentsApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HomePage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Email = "Merlin.Monahan@hotmail.com",
                            HomePage = "",
                            Username = "Vivienne_Cronin35"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Stanford.Ziemann@yahoo.com",
                            HomePage = "",
                            Username = "Kali_Hodkiewicz"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Lydia.Cummings@hotmail.com",
                            HomePage = "",
                            Username = "Georgette_Trantow84"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Justine.Koss49@hotmail.com",
                            HomePage = "https://lon.org",
                            Username = "Johathan.Kunze"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Electa58@hotmail.com",
                            HomePage = "https://gretchen.name",
                            Username = "Floy.Bailey2"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Cedrick_Barrows88@gmail.com",
                            HomePage = "",
                            Username = "Alicia_Berge"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Alysson_Gutmann@yahoo.com",
                            HomePage = "",
                            Username = "Fredrick_Legros"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Lynn_Gottlieb16@yahoo.com",
                            HomePage = "",
                            Username = "Sheridan_Reynolds31"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Karlie.Koelpin8@yahoo.com",
                            HomePage = "",
                            Username = "Vernon5"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Leora.Lind76@gmail.com",
                            HomePage = "",
                            Username = "Reid64"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Genoveva.Mitchell45@hotmail.com",
                            HomePage = "https://ulices.name",
                            Username = "Camron.Harris72"
                        },
                        new
                        {
                            Id = 31,
                            Email = "Phoebe_Price5@gmail.com",
                            HomePage = "",
                            Username = "Katheryn_King81"
                        },
                        new
                        {
                            Id = 32,
                            Email = "Freida_Watsica@hotmail.com",
                            HomePage = "http://rebecca.net",
                            Username = "Katelyn_OReilly"
                        },
                        new
                        {
                            Id = 33,
                            Email = "Hellen_Pouros6@yahoo.com",
                            HomePage = "",
                            Username = "Isobel98"
                        },
                        new
                        {
                            Id = 34,
                            Email = "Queenie_Emard83@yahoo.com",
                            HomePage = "",
                            Username = "Cordelia.Kuhlman35"
                        },
                        new
                        {
                            Id = 35,
                            Email = "Granville98@yahoo.com",
                            HomePage = "",
                            Username = "Julian_Dibbert"
                        },
                        new
                        {
                            Id = 36,
                            Email = "Kali.Lakin@hotmail.com",
                            HomePage = "",
                            Username = "Assunta66"
                        },
                        new
                        {
                            Id = 37,
                            Email = "Teresa53@yahoo.com",
                            HomePage = "http://vinnie.name",
                            Username = "Leda.Heaney"
                        },
                        new
                        {
                            Id = 38,
                            Email = "Ellie.Tillman26@gmail.com",
                            HomePage = "https://shaniya.net",
                            Username = "Toy_Mills55"
                        },
                        new
                        {
                            Id = 39,
                            Email = "Ethel.Denesik@hotmail.com",
                            HomePage = "",
                            Username = "Taya.Gleason67"
                        },
                        new
                        {
                            Id = 40,
                            Email = "Pedro.Cassin6@hotmail.com",
                            HomePage = "",
                            Username = "Milan_Doyle"
                        },
                        new
                        {
                            Id = 41,
                            Email = "Ned_Ferry@gmail.com",
                            HomePage = "",
                            Username = "Rebecca84"
                        },
                        new
                        {
                            Id = 42,
                            Email = "Rigoberto_Green41@yahoo.com",
                            HomePage = "http://beau.info",
                            Username = "Alford27"
                        },
                        new
                        {
                            Id = 43,
                            Email = "Donavon_Spencer99@yahoo.com",
                            HomePage = "",
                            Username = "Aylin35"
                        },
                        new
                        {
                            Id = 44,
                            Email = "Brook_Jerde@hotmail.com",
                            HomePage = "",
                            Username = "Nico_Altenwerth58"
                        },
                        new
                        {
                            Id = 45,
                            Email = "Vilma_Mitchell@hotmail.com",
                            HomePage = "",
                            Username = "Ashley96"
                        },
                        new
                        {
                            Id = 46,
                            Email = "Tatum.OConnell89@hotmail.com",
                            HomePage = "https://osborne.net",
                            Username = "Rossie_Windler55"
                        },
                        new
                        {
                            Id = 47,
                            Email = "Wendy.Kuhn@gmail.com",
                            HomePage = "https://camilla.name",
                            Username = "Jackeline47"
                        },
                        new
                        {
                            Id = 48,
                            Email = "Agustina8@yahoo.com",
                            HomePage = "",
                            Username = "Horace96"
                        },
                        new
                        {
                            Id = 49,
                            Email = "Erica_Schneider42@yahoo.com",
                            HomePage = "",
                            Username = "Alexandra76"
                        },
                        new
                        {
                            Id = 50,
                            Email = "Jacinthe34@yahoo.com",
                            HomePage = "https://monroe.info",
                            Username = "Geovanni.Tromp"
                        },
                        new
                        {
                            Id = 51,
                            Email = "Ramon.Terry99@gmail.com",
                            HomePage = "",
                            Username = "Cristopher92"
                        },
                        new
                        {
                            Id = 52,
                            Email = "Lawrence72@gmail.com",
                            HomePage = "http://wilford.info",
                            Username = "Guido87"
                        },
                        new
                        {
                            Id = 53,
                            Email = "Neil33@hotmail.com",
                            HomePage = "",
                            Username = "Pattie_Schmitt"
                        },
                        new
                        {
                            Id = 54,
                            Email = "Nickolas.Lueilwitz@hotmail.com",
                            HomePage = "",
                            Username = "Katheryn88"
                        },
                        new
                        {
                            Id = 55,
                            Email = "Warren_Robel@yahoo.com",
                            HomePage = "",
                            Username = "Lia.Ryan"
                        },
                        new
                        {
                            Id = 56,
                            Email = "Cooper3@gmail.com",
                            HomePage = "",
                            Username = "Albin80"
                        },
                        new
                        {
                            Id = 57,
                            Email = "Garfield_Green47@yahoo.com",
                            HomePage = "",
                            Username = "Connor7"
                        },
                        new
                        {
                            Id = 58,
                            Email = "Cayla76@gmail.com",
                            HomePage = "",
                            Username = "Adolphus86"
                        },
                        new
                        {
                            Id = 59,
                            Email = "Floyd_Frami50@yahoo.com",
                            HomePage = "http://grady.net",
                            Username = "Bruce_Rippin"
                        },
                        new
                        {
                            Id = 60,
                            Email = "Marlen.Bahringer83@gmail.com",
                            HomePage = "",
                            Username = "Sylvester_Quitzon"
                        },
                        new
                        {
                            Id = 61,
                            Email = "Dorothy.Gleason@hotmail.com",
                            HomePage = "",
                            Username = "Breana.Bergnaum3"
                        },
                        new
                        {
                            Id = 62,
                            Email = "Wade_Herzog68@gmail.com",
                            HomePage = "",
                            Username = "Morris1"
                        },
                        new
                        {
                            Id = 63,
                            Email = "Tyree.Boehm68@hotmail.com",
                            HomePage = "",
                            Username = "Garret60"
                        },
                        new
                        {
                            Id = 64,
                            Email = "Jermain.Mayert78@yahoo.com",
                            HomePage = "",
                            Username = "Patrick30"
                        },
                        new
                        {
                            Id = 65,
                            Email = "Lucienne.Becker@gmail.com",
                            HomePage = "",
                            Username = "Tressa30"
                        },
                        new
                        {
                            Id = 66,
                            Email = "Claude62@yahoo.com",
                            HomePage = "",
                            Username = "Erich_Kunde80"
                        },
                        new
                        {
                            Id = 67,
                            Email = "Name.Hauck0@hotmail.com",
                            HomePage = "",
                            Username = "Edwin.Feest"
                        },
                        new
                        {
                            Id = 68,
                            Email = "Hilma_Sporer@gmail.com",
                            HomePage = "",
                            Username = "Rowan32"
                        },
                        new
                        {
                            Id = 69,
                            Email = "Emilie38@yahoo.com",
                            HomePage = "",
                            Username = "Lavina_Moore"
                        });
                });

            modelBuilder.Entity("CommentsApp.Models.Comment", b =>
                {
                    b.HasOne("CommentsApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
