// <auto-generated />
using CommentsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommentsApp.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241011115951_add seed data")]
    partial class addseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommentsApp.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Text = "Est maxime aut quis vel ut porro sed eligendi aut. Rerum hic ut deleniti odit omnis corrupti id. Optio est dolorum sit aliquam fugit nihil excepturi.",
                            UserId = 59
                        },
                        new
                        {
                            Id = 21,
                            Text = "iure",
                            UserId = 57
                        },
                        new
                        {
                            Id = 22,
                            Text = "Culpa sint qui laudantium perspiciatis.\nDucimus et qui omnis.\nEt ut nisi.\nFuga consequuntur eos laudantium quaerat a consequuntur repellendus doloremque ut.\nQuia quod est quos a hic.",
                            UserId = 28
                        },
                        new
                        {
                            Id = 23,
                            Text = "Et voluptatem adipisci deleniti magnam repellendus saepe.\nDolores praesentium architecto dolorem fugiat.\nVoluptatem id tempora occaecati voluptate blanditiis.\nAut velit et aut impedit eius labore aut.\nAtque maxime ducimus autem.\nOdit rerum voluptatibus.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 24,
                            Text = "incidunt",
                            UserId = 46
                        },
                        new
                        {
                            Id = 25,
                            Text = "Eaque et nemo incidunt aliquid est. Adipisci odio vero molestias dolorem consequuntur rem ut. Et qui delectus reiciendis sit quisquam praesentium. Sequi distinctio et excepturi ut. Velit eius reprehenderit libero. Et voluptates consequatur qui dignissimos fugiat unde consequatur occaecati et.",
                            UserId = 33
                        },
                        new
                        {
                            Id = 26,
                            Text = "Est culpa beatae molestiae eum et. Ducimus itaque architecto eligendi deleniti. Sapiente numquam expedita quis. Praesentium et id expedita est repellat. Qui repellendus quo earum accusamus debitis voluptas.",
                            UserId = 56
                        },
                        new
                        {
                            Id = 27,
                            Text = "fuga",
                            UserId = 52
                        },
                        new
                        {
                            Id = 28,
                            Text = "nostrum",
                            UserId = 48
                        },
                        new
                        {
                            Id = 29,
                            Text = "Aut non omnis delectus optio.\nTemporibus eos numquam nulla ex perferendis qui.\nNon beatae voluptate nobis veniam id molestias et velit pariatur.\nAspernatur suscipit similique sed repellat accusamus eos nulla.\nSoluta porro labore iste ducimus velit.",
                            UserId = 66
                        },
                        new
                        {
                            Id = 30,
                            Text = "expedita",
                            UserId = 21
                        },
                        new
                        {
                            Id = 31,
                            Text = "Enim tempore quo ipsa rerum aut voluptatem ab.",
                            UserId = 62
                        },
                        new
                        {
                            Id = 32,
                            Text = "Eius mollitia magnam eius voluptas numquam reiciendis dolores ipsum ut. Numquam voluptas pariatur ut vitae. Molestiae voluptate dolorem consequatur doloremque repellendus distinctio at. Fugit maiores perspiciatis autem provident est. Voluptas suscipit pariatur hic nihil placeat dignissimos illo maiores unde.",
                            UserId = 68
                        },
                        new
                        {
                            Id = 33,
                            Text = "Velit aperiam facilis ut quis nihil.",
                            UserId = 45
                        },
                        new
                        {
                            Id = 34,
                            Text = "Vel deserunt consequatur fugiat.\nDoloribus tenetur autem.\nEt incidunt excepturi sint eum dolores aut soluta delectus.\nVel atque qui.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 35,
                            Text = "Vitae nisi nemo quam aut.",
                            UserId = 33
                        },
                        new
                        {
                            Id = 36,
                            Text = "Voluptatem eaque ea laboriosam repudiandae nisi et aperiam quia.",
                            UserId = 27
                        },
                        new
                        {
                            Id = 37,
                            Text = "Occaecati quaerat aut qui quod sed blanditiis neque. Doloribus suscipit aut ut sit est est tenetur. Tempora illum est commodi ut omnis quidem voluptas. Quae ut enim cum aliquid sunt est.",
                            UserId = 48
                        },
                        new
                        {
                            Id = 38,
                            Text = "quia",
                            UserId = 21
                        },
                        new
                        {
                            Id = 39,
                            Text = "Sapiente dolorum ducimus ab voluptatem voluptas autem quia.",
                            UserId = 40
                        },
                        new
                        {
                            Id = 40,
                            Text = "Iusto soluta ducimus sapiente.",
                            UserId = 27
                        },
                        new
                        {
                            Id = 41,
                            Text = "Reiciendis repudiandae voluptate illum qui enim voluptatibus et recusandae. Error dignissimos non nisi quos at. Sint ullam facere. Iure ullam et a sunt.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 42,
                            Text = "Voluptate dolorem aut ut iure qui iste aut.\nId ipsa voluptate.\nAccusamus at earum nostrum explicabo amet.\nAt ut laborum sunt ducimus officia et.\nVero corporis quasi enim minima quis quae in error.",
                            UserId = 53
                        },
                        new
                        {
                            Id = 43,
                            Text = "Ullam et natus quo et. Molestiae est sit quibusdam ratione atque quae autem quia omnis. Illum quibusdam quia omnis rerum. Libero qui consequuntur sequi qui blanditiis vel et. Occaecati exercitationem iste consequatur.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 44,
                            Text = "Amet alias voluptas quas et eum ut dolores. Nulla aliquam nulla sequi praesentium cupiditate ex quia saepe. Omnis autem id voluptatem quidem ipsum aut sapiente placeat labore. Et ducimus enim nesciunt voluptatem est aut labore placeat. Necessitatibus distinctio hic laborum consequuntur dolor voluptatibus inventore est velit.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 45,
                            Text = "officiis",
                            UserId = 58
                        },
                        new
                        {
                            Id = 46,
                            Text = "Quia suscipit repudiandae et atque quaerat et nisi. In repellat odio facere magnam aut ratione vitae necessitatibus. Expedita impedit molestias reprehenderit. Et reiciendis eaque. Laboriosam in quas nemo odio dicta eveniet.",
                            UserId = 65
                        },
                        new
                        {
                            Id = 47,
                            Text = "Ea rerum ut quia sed maiores. Voluptatem rerum consequatur perferendis autem debitis porro. Aut optio earum necessitatibus a molestias eius molestias alias incidunt.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 48,
                            Text = "Ex aut enim quae atque qui assumenda dignissimos.\nAmet eaque quis a.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 49,
                            Text = "voluptas",
                            UserId = 59
                        },
                        new
                        {
                            Id = 50,
                            Text = "Fugit velit sapiente rerum beatae eveniet sit.\nVoluptatem sunt magni nostrum et ex.\nReprehenderit nihil maxime qui doloribus sequi provident.\nPossimus pariatur tempore unde magni ipsam cum.",
                            UserId = 42
                        },
                        new
                        {
                            Id = 51,
                            Text = "Atque omnis sequi.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 52,
                            Text = "Officia perspiciatis reprehenderit dolor explicabo inventore maxime tempore animi et.",
                            UserId = 59
                        },
                        new
                        {
                            Id = 53,
                            Text = "Mollitia ea culpa est.\nAspernatur voluptate ut illo.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 54,
                            Text = "Amet magni aut iusto eum suscipit omnis aut.\nVoluptas ex esse cumque aut repellat.\nEt sint illo velit eius molestias quia ut totam aut.\nError et quos voluptas deserunt.\nAutem natus ut autem veritatis quam.",
                            UserId = 34
                        },
                        new
                        {
                            Id = 55,
                            Text = "Sequi mollitia modi enim molestias asperiores.",
                            UserId = 40
                        },
                        new
                        {
                            Id = 56,
                            Text = "Unde provident ut laudantium soluta consequatur.",
                            UserId = 61
                        },
                        new
                        {
                            Id = 57,
                            Text = "Numquam error tenetur. Voluptas delectus quia perspiciatis blanditiis sequi. Aspernatur assumenda voluptatem quibusdam ex non placeat. Exercitationem ad sequi nulla. Omnis inventore numquam.",
                            UserId = 65
                        },
                        new
                        {
                            Id = 58,
                            Text = "Aspernatur voluptas eius quae vero sed nesciunt praesentium corporis sit. Hic et vero qui voluptas vitae. Voluptas deleniti sunt assumenda veniam autem inventore quisquam. Distinctio nihil facere esse nam molestiae velit totam aliquam unde. Itaque sequi consequatur.",
                            UserId = 34
                        },
                        new
                        {
                            Id = 59,
                            Text = "Quia animi non voluptas nostrum dolores et omnis illo. Voluptas natus nihil doloribus eos voluptatem et facere omnis. Repellendus accusantium ipsa iure adipisci numquam reiciendis minus quia.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 60,
                            Text = "Ut pariatur sed tempore. Velit et quia fugit accusamus. Eos optio quia fugit et. Et provident nisi nisi ipsa sit iste qui magni. Sequi excepturi autem. Et blanditiis reprehenderit blanditiis eos sit facilis dolorem laboriosam recusandae.",
                            UserId = 49
                        },
                        new
                        {
                            Id = 61,
                            Text = "Dolore dolores sunt eos non laboriosam magnam ut.\nDolorem non libero natus pariatur sed suscipit.",
                            UserId = 43
                        },
                        new
                        {
                            Id = 62,
                            Text = "Quaerat nobis nemo libero reiciendis dolor amet optio consectetur voluptate.\nQuis accusantium voluptas sunt harum maiores exercitationem culpa.\nNobis et molestiae.\nNon rem blanditiis quibusdam sapiente consequatur voluptatum.\nNon eius blanditiis error consectetur nihil rerum voluptatem voluptatem iste.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 63,
                            Text = "beatae",
                            UserId = 47
                        },
                        new
                        {
                            Id = 64,
                            Text = "Sunt aliquid dolorem vitae nihil.\nPraesentium possimus maxime eos.\nVoluptas reprehenderit minus amet recusandae illum dignissimos.\nIure aut dignissimos natus voluptate et rerum magni est.\nCorrupti ut eum id cupiditate reprehenderit et nemo pariatur.",
                            UserId = 31
                        },
                        new
                        {
                            Id = 65,
                            Text = "Dignissimos veniam vel dolorem omnis qui necessitatibus amet voluptatem. Fugiat sit ut. Temporibus possimus et illum. Id tenetur aliquam. Cum officia accusamus nisi. Et delectus numquam quo reprehenderit velit repellat.",
                            UserId = 33
                        },
                        new
                        {
                            Id = 66,
                            Text = "id",
                            UserId = 26
                        },
                        new
                        {
                            Id = 67,
                            Text = "Et tempora vero asperiores ea aliquam voluptatem et omnis.",
                            UserId = 29
                        },
                        new
                        {
                            Id = 68,
                            Text = "Quaerat at consectetur sed cumque ut necessitatibus deleniti ex.",
                            UserId = 48
                        },
                        new
                        {
                            Id = 69,
                            Text = "Repellat earum et dolores sint qui quae eligendi aut ut.",
                            UserId = 36
                        },
                        new
                        {
                            Id = 70,
                            Text = "enim",
                            UserId = 54
                        },
                        new
                        {
                            Id = 71,
                            Text = "laborum",
                            UserId = 24
                        },
                        new
                        {
                            Id = 72,
                            Text = "Aut voluptatibus magni nisi aut nesciunt voluptas quis ut.\nDeleniti inventore recusandae a asperiores laudantium consectetur magni aliquid.",
                            UserId = 61
                        },
                        new
                        {
                            Id = 73,
                            Text = "porro",
                            UserId = 22
                        },
                        new
                        {
                            Id = 74,
                            Text = "Neque aut sit illo ad in est.",
                            UserId = 44
                        },
                        new
                        {
                            Id = 75,
                            Text = "Consequatur quisquam voluptas.\nIn cum blanditiis aut quam.",
                            UserId = 33
                        },
                        new
                        {
                            Id = 76,
                            Text = "aliquid",
                            UserId = 54
                        },
                        new
                        {
                            Id = 77,
                            Text = "Voluptatem aliquam fuga sunt non est dolorem facilis aliquid enim.\nA iusto temporibus sunt velit.\nReiciendis expedita totam et asperiores nihil rem quaerat architecto.\nLabore et blanditiis sit suscipit at dignissimos quis incidunt eveniet.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 78,
                            Text = "eaque",
                            UserId = 64
                        },
                        new
                        {
                            Id = 79,
                            Text = "Ex et ut.\nImpedit nobis atque impedit veritatis tenetur voluptatem quia.",
                            UserId = 61
                        },
                        new
                        {
                            Id = 80,
                            Text = "eum",
                            UserId = 62
                        },
                        new
                        {
                            Id = 81,
                            Text = "Eveniet reiciendis maiores odit doloribus esse laboriosam. Et necessitatibus dolorum in quia doloribus suscipit. Omnis sed nemo. Vel ut dolorum enim ut exercitationem ab. Maxime ipsum incidunt sed enim aspernatur.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 82,
                            Text = "quis",
                            UserId = 39
                        },
                        new
                        {
                            Id = 83,
                            Text = "Quia dolorum qui dignissimos vel.\nSuscipit dolores ipsa.\nVoluptatem non illo.",
                            UserId = 30
                        },
                        new
                        {
                            Id = 84,
                            Text = "Sed eligendi consequatur itaque assumenda eligendi expedita esse. Accusantium aut modi quod consequatur. Sunt dolorem sed aliquid et eum occaecati enim porro et. Odit repudiandae cum aliquam saepe sit possimus distinctio.",
                            UserId = 29
                        },
                        new
                        {
                            Id = 85,
                            Text = "Voluptate molestiae neque doloremque fugit repellat. Ad ullam optio suscipit iusto necessitatibus. In omnis rerum. Quam et aperiam et officia maxime id aut. Optio laudantium vitae dolor. Dolore id quibusdam nihil.",
                            UserId = 51
                        },
                        new
                        {
                            Id = 86,
                            Text = "Voluptatem et ea voluptate culpa. Consequatur saepe est sed. Quas iusto adipisci reprehenderit laboriosam laboriosam quam exercitationem odit. Possimus vel eius sint quia consectetur voluptatem sed voluptatem.",
                            UserId = 65
                        },
                        new
                        {
                            Id = 87,
                            Text = "minima",
                            UserId = 27
                        },
                        new
                        {
                            Id = 88,
                            Text = "Nam sit dolorem quos rerum labore.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 89,
                            Text = "Cum est ab ut blanditiis.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 90,
                            Text = "quas",
                            UserId = 34
                        },
                        new
                        {
                            Id = 91,
                            Text = "Illum sit necessitatibus quis illo eius est.",
                            UserId = 42
                        },
                        new
                        {
                            Id = 92,
                            Text = "Tempora quis et doloribus cum sequi aliquam et.",
                            UserId = 43
                        },
                        new
                        {
                            Id = 93,
                            Text = "Repudiandae voluptas occaecati eos aut placeat veritatis.\nCulpa reiciendis maxime rerum qui deleniti nostrum autem.\nQuam unde harum ut laborum ducimus.\nMagnam ea dolor non delectus cumque.\nEst voluptas ut ut quae at sint esse earum.",
                            UserId = 39
                        },
                        new
                        {
                            Id = 94,
                            Text = "Ut sint ea adipisci.\nPraesentium consequatur quae vitae aperiam culpa ullam reprehenderit fugit.",
                            UserId = 64
                        },
                        new
                        {
                            Id = 95,
                            Text = "Magni minus debitis ratione ut ipsa voluptatem numquam et earum.",
                            UserId = 45
                        },
                        new
                        {
                            Id = 96,
                            Text = "id",
                            UserId = 31
                        },
                        new
                        {
                            Id = 97,
                            Text = "Sed eos suscipit tenetur qui et quas.",
                            UserId = 36
                        },
                        new
                        {
                            Id = 98,
                            Text = "Nobis delectus expedita id doloremque ut aut voluptatem eos. Aut sunt officiis vitae. Dolorum sint nulla eaque voluptatum quibusdam quia quibusdam consectetur aliquam. Quos eum et tempora perspiciatis ex minima. Harum dolore officia quia.",
                            UserId = 44
                        },
                        new
                        {
                            Id = 99,
                            Text = "harum",
                            UserId = 68
                        },
                        new
                        {
                            Id = 100,
                            Text = "Nostrum laudantium officiis.\nDignissimos doloribus corrupti facere eius aut deleniti.\nTotam deleniti deleniti voluptatum.",
                            UserId = 49
                        },
                        new
                        {
                            Id = 101,
                            Text = "quidem",
                            UserId = 54
                        },
                        new
                        {
                            Id = 102,
                            Text = "Ducimus id aperiam nemo ex repellat nulla dolorem.\nCupiditate dicta delectus sunt dolorum dolor dolorum labore.\nId inventore modi.",
                            UserId = 27
                        },
                        new
                        {
                            Id = 103,
                            Text = "quia",
                            UserId = 56
                        },
                        new
                        {
                            Id = 104,
                            Text = "natus",
                            UserId = 21
                        },
                        new
                        {
                            Id = 105,
                            Text = "Ex asperiores dolorem nihil accusamus voluptate soluta. Facere quis amet repellendus. Vel excepturi iure vero vel culpa in quidem. Ut velit nostrum distinctio. Culpa ut odio aut illo illum earum minus ut voluptatem. Repudiandae non iste sint.",
                            UserId = 62
                        },
                        new
                        {
                            Id = 106,
                            Text = "Molestiae maxime numquam dolorum cumque.\nConsectetur deleniti rerum non.",
                            UserId = 58
                        },
                        new
                        {
                            Id = 107,
                            Text = "Quia dolores aut repellendus.",
                            UserId = 35
                        },
                        new
                        {
                            Id = 108,
                            Text = "Cumque facilis perspiciatis consequuntur nam eveniet consequatur voluptas porro nostrum.\nQuis et incidunt dolorem commodi est id.",
                            UserId = 48
                        },
                        new
                        {
                            Id = 109,
                            Text = "Occaecati non pariatur et nihil quo blanditiis magni sed sed. Ea est aspernatur tempore dolores eaque voluptas dolorem quidem tempora. Numquam ipsa non reiciendis voluptas id veritatis culpa doloribus ut. Nihil quia suscipit ad mollitia adipisci et eum.",
                            UserId = 49
                        },
                        new
                        {
                            Id = 110,
                            Text = "Sint quas et est tempora optio. Eaque cumque est animi. Aut vero est eum quisquam quasi tenetur consequuntur rerum omnis. Aut laboriosam modi.",
                            UserId = 42
                        },
                        new
                        {
                            Id = 111,
                            Text = "ipsum",
                            UserId = 32
                        },
                        new
                        {
                            Id = 112,
                            Text = "In eligendi rem voluptatem quae quo rerum maxime incidunt.\nNon cupiditate laboriosam totam quod rem ut nam sint aut.",
                            UserId = 35
                        },
                        new
                        {
                            Id = 113,
                            Text = "Explicabo aliquid alias aliquam fugit accusamus. Magni iusto non tempora neque magnam. Tempore incidunt quasi. Velit at sunt qui alias facere. Distinctio ut deserunt quia ea atque facere tenetur.",
                            UserId = 69
                        },
                        new
                        {
                            Id = 114,
                            Text = "optio",
                            UserId = 61
                        },
                        new
                        {
                            Id = 115,
                            Text = "Deleniti quibusdam dicta consequuntur labore.\nEius ratione doloribus quis minus et velit.\nReprehenderit rerum ut dolore iste qui delectus at aut beatae.\nVoluptatum quia quaerat tenetur aut qui odio facere.\nQuis nostrum commodi.",
                            UserId = 63
                        },
                        new
                        {
                            Id = 116,
                            Text = "Possimus animi quo fuga natus laboriosam.\nAnimi non ut.",
                            UserId = 49
                        },
                        new
                        {
                            Id = 117,
                            Text = "quia",
                            UserId = 39
                        },
                        new
                        {
                            Id = 118,
                            Text = "In voluptas quis.\nConsectetur sit necessitatibus exercitationem dolorem commodi excepturi aspernatur ad voluptatum.\nIusto aut non magnam ipsum blanditiis dolorem dolores.\nDistinctio molestiae fuga consequatur.\nIn et maxime et ex.",
                            UserId = 43
                        },
                        new
                        {
                            Id = 119,
                            Text = "Similique qui rerum sit qui aut. Quas magnam officiis at quidem dolorem amet. Dolorum iste incidunt harum ut ullam. Reprehenderit vitae non officia quo voluptas mollitia et repellat. Est cupiditate rerum nam modi quia assumenda nesciunt culpa sequi.",
                            UserId = 28
                        },
                        new
                        {
                            Id = 120,
                            Text = "Velit totam quis aut et et sed excepturi. Aut adipisci et in. Voluptatem autem voluptates voluptas officiis accusamus hic facilis perspiciatis. Qui et praesentium rem expedita qui qui rerum. Sed dolor dolore qui. Sed possimus et dolor suscipit quo rem ea.",
                            UserId = 56
                        },
                        new
                        {
                            Id = 121,
                            Text = "Dolore pariatur debitis dicta omnis assumenda et distinctio corrupti. Dolor facilis vero ipsa modi. Id adipisci et sit qui adipisci non. Consequatur est nemo. Ut aperiam nihil dolores culpa accusamus eveniet minus. Ipsa nihil velit quia id tempora placeat reiciendis eius.",
                            UserId = 36
                        },
                        new
                        {
                            Id = 122,
                            Text = "Sint dolorum non laboriosam debitis reprehenderit ab.",
                            UserId = 51
                        },
                        new
                        {
                            Id = 123,
                            Text = "Praesentium numquam nihil. Nam veniam et doloribus ratione corrupti. Optio est numquam eligendi expedita ut laudantium qui temporibus.",
                            UserId = 42
                        },
                        new
                        {
                            Id = 124,
                            Text = "sunt",
                            UserId = 35
                        },
                        new
                        {
                            Id = 125,
                            Text = "Nesciunt cumque voluptatum nulla.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 126,
                            Text = "sapiente",
                            UserId = 40
                        },
                        new
                        {
                            Id = 127,
                            Text = "Omnis vitae eligendi voluptatem sit. Consequuntur consequuntur molestiae possimus. Amet minus vitae.",
                            UserId = 28
                        },
                        new
                        {
                            Id = 128,
                            Text = "Ducimus quia odit eaque corrupti consequuntur consequatur.\nUllam reprehenderit temporibus id aliquid voluptatem qui.\nConsectetur vel ducimus rerum sed.",
                            UserId = 63
                        },
                        new
                        {
                            Id = 129,
                            Text = "Quam aperiam sint quod voluptas sint. Tempore et quas maiores quia id. Error repellendus illum pariatur id suscipit amet.",
                            UserId = 40
                        },
                        new
                        {
                            Id = 130,
                            Text = "Necessitatibus quibusdam ipsum et iusto culpa. Repudiandae unde et explicabo. Est sed voluptatum velit veritatis corrupti omnis mollitia eos. Repellendus rerum vero corporis sit tempora. Corporis sit quia repudiandae aliquid officiis quia non voluptatem.",
                            UserId = 41
                        },
                        new
                        {
                            Id = 131,
                            Text = "Consectetur non rem non quae. Voluptatem molestiae quia sint aspernatur. Dolore iusto aut. Autem magni error non inventore. Ab et itaque quam. Aliquid velit ipsa illo voluptas assumenda pariatur voluptatem.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 132,
                            Text = "Aliquam nihil delectus non dolor aspernatur architecto voluptates odit iusto.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 133,
                            Text = "Ex eveniet ut rerum voluptatum. Asperiores fuga est voluptates est vitae et. Ut in quia facere accusamus.",
                            UserId = 63
                        },
                        new
                        {
                            Id = 134,
                            Text = "Consequuntur et tenetur nulla doloremque ipsam modi et ad illum. Atque officiis laborum ipsam dolor et non et illo. Quia explicabo incidunt. Cum nihil voluptatem ea inventore ex nihil et itaque. Debitis cupiditate nihil. Enim nihil nam qui ut aut omnis commodi repellendus vero.",
                            UserId = 68
                        },
                        new
                        {
                            Id = 135,
                            Text = "earum",
                            UserId = 32
                        },
                        new
                        {
                            Id = 136,
                            Text = "Ut quisquam doloremque ex laborum sapiente aut numquam praesentium sit. Recusandae molestias iusto aliquam neque delectus voluptatem et qui facere. Quia eaque enim sint ea reprehenderit illo esse dolor. Aperiam sit et aut tempore laborum cumque laudantium. Ut aut omnis autem molestiae minima nihil quo voluptas. Molestiae ipsum molestias ipsum qui mollitia asperiores ipsa eligendi iste.",
                            UserId = 44
                        },
                        new
                        {
                            Id = 137,
                            Text = "quae",
                            UserId = 27
                        },
                        new
                        {
                            Id = 138,
                            Text = "Quia non qui corrupti ex dolorum dolorem laborum sint voluptatem.",
                            UserId = 37
                        },
                        new
                        {
                            Id = 139,
                            Text = "rerum",
                            UserId = 52
                        },
                        new
                        {
                            Id = 140,
                            Text = "Odio magnam cupiditate non. Voluptas non soluta. Aut et quis beatae omnis fuga molestias. Tenetur saepe voluptatem aliquid dolorum nemo consequatur. Et sed magnam facere nesciunt ab in illum rerum id.",
                            UserId = 65
                        },
                        new
                        {
                            Id = 141,
                            Text = "Voluptas et consequatur repellendus laborum. Voluptas odio voluptatem quisquam id. Nobis sunt esse eos illum. Occaecati harum commodi facilis a non velit a sit totam.",
                            UserId = 26
                        },
                        new
                        {
                            Id = 142,
                            Text = "quisquam",
                            UserId = 57
                        },
                        new
                        {
                            Id = 143,
                            Text = "est",
                            UserId = 26
                        },
                        new
                        {
                            Id = 144,
                            Text = "perspiciatis",
                            UserId = 61
                        },
                        new
                        {
                            Id = 145,
                            Text = "Numquam vero non perferendis et consequatur corrupti.\nVitae repellendus sapiente et quod rerum.\nVeniam aut quis.\nNon vero corporis aut alias doloribus quia eaque.\nReprehenderit voluptatem voluptatibus et est et voluptatem repellendus molestiae repudiandae.",
                            UserId = 50
                        },
                        new
                        {
                            Id = 146,
                            Text = "Ab quis possimus.\nVelit cumque aut id nam laudantium ipsa.\nImpedit voluptates facere non accusantium mollitia voluptas non aut.\nEt porro rem tempore quibusdam sit at ut omnis.\nSunt temporibus magnam.\nDolore corrupti autem suscipit hic expedita et occaecati.",
                            UserId = 30
                        },
                        new
                        {
                            Id = 147,
                            Text = "Aperiam ut rerum sit. Ipsam illo quis similique eaque. Quod et cum. Eligendi nihil voluptatibus est et expedita voluptatem veniam sed et.",
                            UserId = 69
                        },
                        new
                        {
                            Id = 148,
                            Text = "Veniam sint excepturi.\nIste ullam tenetur vitae maxime.\nEst id delectus neque quia praesentium ab molestiae ad.",
                            UserId = 58
                        },
                        new
                        {
                            Id = 149,
                            Text = "Incidunt iusto qui aut. Aliquid numquam enim id optio dolor quis. Sint nihil aliquid autem non laborum a. Hic sit eligendi vero. Beatae facere error. Qui voluptatem totam ullam minima.",
                            UserId = 64
                        },
                        new
                        {
                            Id = 150,
                            Text = "Minus non non aperiam eaque. Debitis nobis earum fuga beatae eveniet nulla ut vero. Veniam magnam saepe. Perspiciatis enim praesentium nihil.",
                            UserId = 41
                        },
                        new
                        {
                            Id = 151,
                            Text = "doloremque",
                            UserId = 60
                        },
                        new
                        {
                            Id = 152,
                            Text = "ut",
                            UserId = 47
                        },
                        new
                        {
                            Id = 153,
                            Text = "Deserunt debitis et.",
                            UserId = 52
                        },
                        new
                        {
                            Id = 154,
                            Text = "Reiciendis iure eos consequuntur atque in quod et laborum voluptatem. Et vitae dolores autem praesentium et qui mollitia et facere. Laudantium nihil vitae.",
                            UserId = 55
                        },
                        new
                        {
                            Id = 155,
                            Text = "Nihil eum consequatur aut maiores quia. Dolores suscipit modi eaque. Incidunt quia a labore sint exercitationem. Et quam commodi fugiat ipsam tempora sequi sint molestiae et.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 156,
                            Text = "Sit amet aut harum cupiditate aspernatur. Quidem voluptas minus animi natus unde cupiditate at quas totam. Ea eos ducimus ab. Omnis ab debitis. Aliquam tempora cumque quis iusto ducimus rerum eveniet voluptatem.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 157,
                            Text = "Doloribus dolorem explicabo harum.\nPossimus cum harum et.\nDelectus aut vel qui eaque veniam.",
                            UserId = 26
                        },
                        new
                        {
                            Id = 158,
                            Text = "Facilis ut impedit voluptate fuga dignissimos neque.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 159,
                            Text = "Nihil eos est quia officiis veniam a et voluptatem.\nSed velit amet aut id.\nInventore quisquam nulla laborum ut placeat.\nMaxime non minima.\nTotam amet et facilis sit consequatur labore repellat odit.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 160,
                            Text = "vero",
                            UserId = 57
                        },
                        new
                        {
                            Id = 161,
                            Text = "Aut quis dignissimos quasi occaecati id necessitatibus eaque.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 162,
                            Text = "Perferendis non cum quo doloremque ad deserunt non corrupti.",
                            UserId = 32
                        },
                        new
                        {
                            Id = 163,
                            Text = "Sit consectetur hic aut harum exercitationem rerum et.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 164,
                            Text = "Id id ullam eos.",
                            UserId = 57
                        },
                        new
                        {
                            Id = 165,
                            Text = "culpa",
                            UserId = 27
                        },
                        new
                        {
                            Id = 166,
                            Text = "Doloribus nemo quia ut. Eveniet voluptatem tempora. Ducimus possimus rerum voluptatem debitis sunt quibusdam quaerat maxime. Non est est est.",
                            UserId = 66
                        },
                        new
                        {
                            Id = 167,
                            Text = "qui",
                            UserId = 40
                        },
                        new
                        {
                            Id = 168,
                            Text = "Aspernatur nostrum in voluptatibus velit rerum atque commodi numquam maiores. Eos ducimus possimus voluptatibus explicabo eaque maiores. Ex quia ea quod. Voluptatum ut qui iure dolorem aliquid corrupti molestiae.",
                            UserId = 62
                        },
                        new
                        {
                            Id = 169,
                            Text = "Et minima cum non ipsam saepe. Ut molestiae et ad delectus a consequatur. Molestiae est sit qui eligendi omnis tempore molestias. Inventore explicabo velit et et quia aut occaecati ea sint.",
                            UserId = 62
                        });
                });

            modelBuilder.Entity("CommentsApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HomePage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Email = "Merlin.Monahan@hotmail.com",
                            HomePage = "",
                            Username = "Vivienne_Cronin35"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Stanford.Ziemann@yahoo.com",
                            HomePage = "",
                            Username = "Kali_Hodkiewicz"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Lydia.Cummings@hotmail.com",
                            HomePage = "",
                            Username = "Georgette_Trantow84"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Justine.Koss49@hotmail.com",
                            HomePage = "https://lon.org",
                            Username = "Johathan.Kunze"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Electa58@hotmail.com",
                            HomePage = "https://gretchen.name",
                            Username = "Floy.Bailey2"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Cedrick_Barrows88@gmail.com",
                            HomePage = "",
                            Username = "Alicia_Berge"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Alysson_Gutmann@yahoo.com",
                            HomePage = "",
                            Username = "Fredrick_Legros"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Lynn_Gottlieb16@yahoo.com",
                            HomePage = "",
                            Username = "Sheridan_Reynolds31"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Karlie.Koelpin8@yahoo.com",
                            HomePage = "",
                            Username = "Vernon5"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Leora.Lind76@gmail.com",
                            HomePage = "",
                            Username = "Reid64"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Genoveva.Mitchell45@hotmail.com",
                            HomePage = "https://ulices.name",
                            Username = "Camron.Harris72"
                        },
                        new
                        {
                            Id = 31,
                            Email = "Phoebe_Price5@gmail.com",
                            HomePage = "",
                            Username = "Katheryn_King81"
                        },
                        new
                        {
                            Id = 32,
                            Email = "Freida_Watsica@hotmail.com",
                            HomePage = "http://rebecca.net",
                            Username = "Katelyn_OReilly"
                        },
                        new
                        {
                            Id = 33,
                            Email = "Hellen_Pouros6@yahoo.com",
                            HomePage = "",
                            Username = "Isobel98"
                        },
                        new
                        {
                            Id = 34,
                            Email = "Queenie_Emard83@yahoo.com",
                            HomePage = "",
                            Username = "Cordelia.Kuhlman35"
                        },
                        new
                        {
                            Id = 35,
                            Email = "Granville98@yahoo.com",
                            HomePage = "",
                            Username = "Julian_Dibbert"
                        },
                        new
                        {
                            Id = 36,
                            Email = "Kali.Lakin@hotmail.com",
                            HomePage = "",
                            Username = "Assunta66"
                        },
                        new
                        {
                            Id = 37,
                            Email = "Teresa53@yahoo.com",
                            HomePage = "http://vinnie.name",
                            Username = "Leda.Heaney"
                        },
                        new
                        {
                            Id = 38,
                            Email = "Ellie.Tillman26@gmail.com",
                            HomePage = "https://shaniya.net",
                            Username = "Toy_Mills55"
                        },
                        new
                        {
                            Id = 39,
                            Email = "Ethel.Denesik@hotmail.com",
                            HomePage = "",
                            Username = "Taya.Gleason67"
                        },
                        new
                        {
                            Id = 40,
                            Email = "Pedro.Cassin6@hotmail.com",
                            HomePage = "",
                            Username = "Milan_Doyle"
                        },
                        new
                        {
                            Id = 41,
                            Email = "Ned_Ferry@gmail.com",
                            HomePage = "",
                            Username = "Rebecca84"
                        },
                        new
                        {
                            Id = 42,
                            Email = "Rigoberto_Green41@yahoo.com",
                            HomePage = "http://beau.info",
                            Username = "Alford27"
                        },
                        new
                        {
                            Id = 43,
                            Email = "Donavon_Spencer99@yahoo.com",
                            HomePage = "",
                            Username = "Aylin35"
                        },
                        new
                        {
                            Id = 44,
                            Email = "Brook_Jerde@hotmail.com",
                            HomePage = "",
                            Username = "Nico_Altenwerth58"
                        },
                        new
                        {
                            Id = 45,
                            Email = "Vilma_Mitchell@hotmail.com",
                            HomePage = "",
                            Username = "Ashley96"
                        },
                        new
                        {
                            Id = 46,
                            Email = "Tatum.OConnell89@hotmail.com",
                            HomePage = "https://osborne.net",
                            Username = "Rossie_Windler55"
                        },
                        new
                        {
                            Id = 47,
                            Email = "Wendy.Kuhn@gmail.com",
                            HomePage = "https://camilla.name",
                            Username = "Jackeline47"
                        },
                        new
                        {
                            Id = 48,
                            Email = "Agustina8@yahoo.com",
                            HomePage = "",
                            Username = "Horace96"
                        },
                        new
                        {
                            Id = 49,
                            Email = "Erica_Schneider42@yahoo.com",
                            HomePage = "",
                            Username = "Alexandra76"
                        },
                        new
                        {
                            Id = 50,
                            Email = "Jacinthe34@yahoo.com",
                            HomePage = "https://monroe.info",
                            Username = "Geovanni.Tromp"
                        },
                        new
                        {
                            Id = 51,
                            Email = "Ramon.Terry99@gmail.com",
                            HomePage = "",
                            Username = "Cristopher92"
                        },
                        new
                        {
                            Id = 52,
                            Email = "Lawrence72@gmail.com",
                            HomePage = "http://wilford.info",
                            Username = "Guido87"
                        },
                        new
                        {
                            Id = 53,
                            Email = "Neil33@hotmail.com",
                            HomePage = "",
                            Username = "Pattie_Schmitt"
                        },
                        new
                        {
                            Id = 54,
                            Email = "Nickolas.Lueilwitz@hotmail.com",
                            HomePage = "",
                            Username = "Katheryn88"
                        },
                        new
                        {
                            Id = 55,
                            Email = "Warren_Robel@yahoo.com",
                            HomePage = "",
                            Username = "Lia.Ryan"
                        },
                        new
                        {
                            Id = 56,
                            Email = "Cooper3@gmail.com",
                            HomePage = "",
                            Username = "Albin80"
                        },
                        new
                        {
                            Id = 57,
                            Email = "Garfield_Green47@yahoo.com",
                            HomePage = "",
                            Username = "Connor7"
                        },
                        new
                        {
                            Id = 58,
                            Email = "Cayla76@gmail.com",
                            HomePage = "",
                            Username = "Adolphus86"
                        },
                        new
                        {
                            Id = 59,
                            Email = "Floyd_Frami50@yahoo.com",
                            HomePage = "http://grady.net",
                            Username = "Bruce_Rippin"
                        },
                        new
                        {
                            Id = 60,
                            Email = "Marlen.Bahringer83@gmail.com",
                            HomePage = "",
                            Username = "Sylvester_Quitzon"
                        },
                        new
                        {
                            Id = 61,
                            Email = "Dorothy.Gleason@hotmail.com",
                            HomePage = "",
                            Username = "Breana.Bergnaum3"
                        },
                        new
                        {
                            Id = 62,
                            Email = "Wade_Herzog68@gmail.com",
                            HomePage = "",
                            Username = "Morris1"
                        },
                        new
                        {
                            Id = 63,
                            Email = "Tyree.Boehm68@hotmail.com",
                            HomePage = "",
                            Username = "Garret60"
                        },
                        new
                        {
                            Id = 64,
                            Email = "Jermain.Mayert78@yahoo.com",
                            HomePage = "",
                            Username = "Patrick30"
                        },
                        new
                        {
                            Id = 65,
                            Email = "Lucienne.Becker@gmail.com",
                            HomePage = "",
                            Username = "Tressa30"
                        },
                        new
                        {
                            Id = 66,
                            Email = "Claude62@yahoo.com",
                            HomePage = "",
                            Username = "Erich_Kunde80"
                        },
                        new
                        {
                            Id = 67,
                            Email = "Name.Hauck0@hotmail.com",
                            HomePage = "",
                            Username = "Edwin.Feest"
                        },
                        new
                        {
                            Id = 68,
                            Email = "Hilma_Sporer@gmail.com",
                            HomePage = "",
                            Username = "Rowan32"
                        },
                        new
                        {
                            Id = 69,
                            Email = "Emilie38@yahoo.com",
                            HomePage = "",
                            Username = "Lavina_Moore"
                        });
                });

            modelBuilder.Entity("CommentsApp.Models.Comment", b =>
                {
                    b.HasOne("CommentsApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
